products = [
  {
    '_id': '1',
    'name': 'Livro do terço dos homens',
    'author': 'Dom Gregório Paixão',
    'image': 'https://m.media-amazon.com/images/I/71TyPj+E5AL._SY466_.jpg',
    'description': 'O Terço dos Homens deseja resgatar, para o seio da Igreja de Cristo, os homens de todas as idades, classes e culturas, pois é notória a sua presença em todas as atividades humanas, mas com visível ausência nas fileiras da Igreja. Entretanto, o Terço dos Homens não se prende apenas à presença masculina. ',
    'publicationDate': '02/04/2022',
    'pages' : 200,
    'publisher' : 'Paulus Editora',
    'category': 'Religião',
    'price': 9.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  }
  # {
  #   '_id': '2',
  #   'name': 'iPhone 11 Pro 256GB Memory',
  #   'image': '/images/phone.jpg',
  #   'description':
  #     'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
  #   'brand': 'Apple',
  #   'category': 'Electronics',
  #   'price': 599.99,
  #   'countInStock': 7,
  #   'rating': 4.0,
  #   'numReviews': 8,
  # },
  # {
  #   '_id': '3',
  #   'name': 'Cannon EOS 80D DSLR Camera',
  #   'image': '/images/camera.jpg',
  #   'description':
  #     'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
  #   'brand': 'Cannon',
  #   'category': 'Electronics',
  #   'price': 929.99,
  #   'countInStock': 5,
  #   'rating': 3,
  #   'numReviews': 12,
  # },
  # {
  #   '_id': '4',
  #   'name': 'Sony Playstation 4 Pro White Version',
  #   'image': '/images/playstation.jpg',
  #   'description':
  #     'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
  #   'brand': 'Sony',
  #   'category': 'Electronics',
  #   'price': 399.99,
  #   'countInStock': 11,
  #   'rating': 5,
  #   'numReviews': 12,
  # },
  # {
  #   '_id': '5',
  #   'name': 'Logitech G-Series Gaming Mouse',
  #   'image': '/images/mouse.jpg',
  #   'description':
  #     'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
  #   'brand': 'Logitech',
  #   'category': 'Electronics',
  #   'price': 49.99,
  #   'countInStock': 7,
  #   'rating': 3.5,
  #   'numReviews': 10,
  # },
  # {
  #   '_id': '6',
  #   'name': 'Amazon Echo Dot 3rd Generation',
  #   'image': '/images/alexa.jpg',
  #   'description':
  #     'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
  #   'brand': 'Amazon',
  #   'category': 'Electronics',
  #   'price': 29.99,
  #   'countInStock': 0,
  #   'rating': 4,
  #   'numReviews': 12,
  # },
]