# Generated by Django 5.1.1 on 2024-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
